apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devconnect

resources:
  - namespace-devconnect.yaml
  - app-secrets.yaml
  - postgres-deployment.yaml
  - auth-service-deployment.yaml
  - profiles-service-deployment.yaml
  - projects-service-deployment.yaml
  - matching-service-deployment.yaml
  - payments-service-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml

